apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: mqtt-broker
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883 # MQTT standard port
        - containerPort: 9001 # WebSocket port (optional)
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # volumeMounts:
        # - mountPath: /mosquitto/config
        #   name: mqtt-config
        #   subPath: mosquitto.conf
      volumes:
      - name: mqtt-config
        configMap:
          name: mqtt-broker-config
