apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  type: NodePort # Change to ClusterIP if internal-only access is needed
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
    name: mqtt
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: mqtt-websocket
  selector:
    app: mqtt-broker
