apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  # jetstream is the new implementation of NATS Streaming Server
  jetstream:
    version: latest # Change this to a specific version in production
    replicas: 1
    startArgs:
      - "-D" # Enable debug logs
    streamConfig: |
      replicas: 1
