apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
resources:
  - namespace.yaml

  - base/install.yaml
  - base/install-validating-webhook.yaml
  - base/sensor-rbac.yaml
  - base/workflow-rbac.yaml

  # Roles
  - cluster-roles/cluster-role.yaml
  - cluster-roles/cluster-rolebinding.yaml

  - event-bus.yaml

  - mqtt/emqx-event-source.yaml
  - mqtt/emqx-sensor.yaml
