apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-cluster-role
rules:
  - apiGroups:
    - argoproj.io
    resources:
    - workflows
    - cronworkflows
    - workflowtemplates
    - clusterworkflowtemplates
    verbs:
    - '*'
